# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


user:
  name: csyaonie
  age: 26
  map: {say: fuck,hello: you}
  list: [1,2,3]
  list2:
    - 3
    - 2
    - 1

address: 厦门市思明区侨岳里${random.int(10)}

mail:
  username: 123456
  password: 123456
  auth: 123456
# 日志配置
logging:
  level:
    com.csyaonie: debug
    org: error

spring:
  datasource:
    username: root
    password: 111-kela
    url: jdbc:mysql://139.224.2.0:3306/springboot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 30000
      maximumPoolSize: 15
  redis:
    host: 139.224.2.0
    port: 6379
    password: 111-kela
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    database: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    enabled: true
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: false
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
      default_encoding: UTF-8
      output_encoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
debug: false